[package]
name = "penis2"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/letx5/penis2.git"
description = "An improved penis generator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
